### ISSUE TITLE
Support multiple msgs in Tx module

### ISSUE THREAD

**Issue by ewoolsey** [de-husk/cosm-tome#7]
The function signature should probably look like this:
```rust
async fn broadcast_tx(&self, tx: &impl IntoIterator<Item = Raw>) -> Result<ChainTxResponse, ChainError>
```
This would be super useful for quickly sending off many txs. @de-husk if you don't have time for this I'd be happy to take a crack at it! My deployment software is regularly sending off 20-30 txs in a row so this would be super useful for me.

**Comment by de-husk** [comment]
:wave: 

I will be making the `tx` module next, and this is a good point. 

I'm curious about your use case though. Are those ~30 transactions all being signed with the same key (or the gas being paid by the same key)? 

If so you can just batch them [under the same Tx](https://github.com/cosmos/cosmos-rust/blob/100f958bcdac3346218542edfa9abe62195985f9/cosmrs/src/tx/body.rs#L14-L22). Otherwise, it doesn't look like cosmosSDK actually supports a batch broadcast functionality, so we would end up having to just call `/cosmos.tx.v1beta1.Service/BroadcastTx` in a loop. Which Im fine with adding a utility method that does that.

**Comment by ewoolsey** [comment]
I was actually looking at what you have in cost-orc. There you have
```rust
pub async fn send_tx(
    client: &HttpClient,
    msg: Any,
    key: &secp256k1::SigningKey,
    account_id: AccountId,
    cfg: &ChainCfg,
)
``` which doesn't support using an Iterator for msg. Ideally when you get the tx module written here having it use `impl IntoIterator<Item = Any>` would be fantastic. Batching them under the same Tx is what I was trying to say. I don't need to batch broadcast many messages, but if you wanted to support that I think you can hack it by manually incrementing the account sequence, although in my testing I've seen that to mostly work, but it was fairly unreliable.

**Comment by de-husk** [comment]
> Ideally when you get the tx module written here having it use impl IntoIterator<Item = Any> would be fantastic.
Perfect, really good call, will do.

**Comment by de-husk** [comment]
Initial version done, check out https://github.com/de-husk/cosm-tome/blob/main/src/modules/tx/api.rs
